/**
 * Extra Hearts — mine Heart Ore, craft Heart Containers, eat them for more hearts.
 *
 * Heart Ore generates underground in the Overworld (feature_rules/): a stone
 * variant in stone, granite, diorite and andesite, and a deepslate variant in
 * deepslate and tuff, like vanilla ores. Breaking either with an iron pickaxe
 * or better drops Heart Fragments; Fortune adds more and Silk Touch drops the
 * ore block instead. Five fragments in a heart shape craft a Heart Container,
 * and eating one adds a permanent heart, up to MAX_HEARTS in total.
 *
 * How the extra health works: Bedrock scripts cannot set an entity's max
 * health directly, so the behavior pack overrides the vanilla player entity
 * (entities/player.json, generated by assets/generate.mjs) and adds one
 * component group per heart count, each carrying a `minecraft:health` with
 * that max. The script triggers `steveo:hearts_<n>` to switch groups. The
 * count itself lives in a player dynamic property, so it survives death,
 * relogging, and Realm uploads; on every spawn and every few seconds the
 * script re-applies the group if the effective max has fallen below it.
 *
 * The block's loot table is empty on purpose: drops are decided here so the
 * pickaxe tier, Fortune, and Silk Touch can be honoured in one place.
 */
import {
  GameMode,
  ItemStack,
  Player,
  system,
  world,
  type Block,
  type Dimension,
  type RawMessage,
  type Vector3,
} from '@minecraft/server';

import { createLogger } from '@shared/log';
import { Format } from '@shared/chat';

const log = createLogger('extra-hearts');
const PREFIX: RawMessage = { text: `${Format.gray}[Extra Hearts]${Format.reset} ` };

const ORE_ID = 'steveo:heart_ore';
const DEEPSLATE_ORE_ID = 'steveo:deepslate_heart_ore';
const ORE_IDS = new Set([ORE_ID, DEEPSLATE_ORE_ID]);
const FRAGMENT_ID = 'steveo:heart_fragment';
const CONTAINER_ID = 'steveo:heart_container';
/** Player dynamic property: number of bonus hearts, 0..(MAX_HEARTS - BASE_HEARTS). */
const BONUS_PROP = 'steveo:extra_hearts';

/** Vanilla max health in hearts; must match the component groups in player.json. */
const BASE_HEARTS = 10;
/** Hard cap on total hearts; the generator writes groups up to this count. */
const MAX_HEARTS = 30;
/** Hearts gained per Heart Container eaten. */
const HEARTS_PER_CONTAINER = 1;

/** Fragments an ore drops before Fortune: a random count in this range. */
const DROP_MIN = 1;
const DROP_MAX = 2;
/** Experience orbs an ore drops, like a vanilla ore. */
const XP_ORBS = 3;
/** Ticks between sweeps that re-apply the health group if the game dropped it. */
const SWEEP_TICKS = 100;
/** Pickaxe tiers good enough to mine Heart Ore, as vanilla item tags. */
const MINING_TIERS = ['minecraft:iron_tier', 'minecraft:diamond_tier', 'minecraft:netherite_tier'];

/**
 * Seeding Heart Ore into chunks that were generated before the pack existed
 * (`/scriptevent steveo:hearts seed`). These mirror features/ and
 * feature_rules/ so seeded ore is about as common as generated ore.
 */
const SEED_REPLACEABLE = new Map<string, string>([
  ['minecraft:stone', ORE_ID],
  ['minecraft:granite', ORE_ID],
  ['minecraft:diorite', ORE_ID],
  ['minecraft:andesite', ORE_ID],
  ['minecraft:deepslate', DEEPSLATE_ORE_ID],
  ['minecraft:tuff', DEEPSLATE_ORE_ID],
]);
const SEED_Y_MIN = -58;
const SEED_Y_MAX = 24;
const SEED_VEINS_PER_CHUNK = 2;
const SEED_VEIN_SIZE = 5;
/** Radius in chunks around the player; loaded chunks only, so keep it small. */
const SEED_RADIUS_DEFAULT = 2;
const SEED_RADIUS_MAX = 4;
/** Block lookups between yields, so a big seed does not stall the tick. */
const SEED_YIELD_EVERY = 64;

// ---------- messages ----------

function say(player: Player, key: string, ...args: string[]): void {
  player.sendMessage([PREFIX, { translate: key, with: args }]);
}

// ---------- heart count ----------

function getBonus(player: Player): number {
  const raw = player.getDynamicProperty(BONUS_PROP);
  if (typeof raw !== 'number' || !Number.isFinite(raw)) return 0;
  return Math.max(0, Math.min(MAX_HEARTS - BASE_HEARTS, Math.floor(raw)));
}

function totalHearts(player: Player): number {
  return BASE_HEARTS + getBonus(player);
}

function effectiveMax(player: Player): number {
  return player.getComponent('minecraft:health')?.effectiveMax ?? BASE_HEARTS * 2;
}

/** Switches the player to the component group for their heart count. */
function applyHearts(player: Player): void {
  const hearts = totalHearts(player);
  const event = hearts === BASE_HEARTS ? 'steveo:hearts_reset' : `steveo:hearts_${hearts}`;
  try {
    player.triggerEvent(event);
  } catch (err) {
    log.error(`could not trigger ${event} on ${player.name}`, err);
  }
}

/**
 * Re-applies the group only when the max has fallen short, e.g. after a
 * respawn. Checking with `<` leaves Health Boost alone: that raises the
 * effective max above ours and must not trigger a reset (which refills health).
 */
function ensureHearts(player: Player): void {
  if (!player.isValid) return;
  if (effectiveMax(player) < totalHearts(player) * 2) applyHearts(player);
}

function setHearts(player: Player, hearts: number): void {
  const clamped = Math.max(BASE_HEARTS, Math.min(MAX_HEARTS, Math.floor(hearts)));
  player.setDynamicProperty(BONUS_PROP, clamped - BASE_HEARTS);
  applyHearts(player);
}

// ---------- eating a Heart Container ----------

world.beforeEvents.itemUse.subscribe((event) => {
  if (event.itemStack.typeId !== CONTAINER_ID) return;
  const player = event.source;
  if (totalHearts(player) < MAX_HEARTS) return;
  event.cancel = true;
  system.run(() => say(player, 'extra_hearts.full', String(MAX_HEARTS)));
});

world.afterEvents.itemCompleteUse.subscribe((event) => {
  if (event.itemStack.typeId !== CONTAINER_ID) return;
  const player = event.source;
  const hearts = Math.min(MAX_HEARTS, totalHearts(player) + HEARTS_PER_CONTAINER);
  setHearts(player, hearts);
  player.playSound('random.levelup', { pitch: 1.3 });
  try {
    player.dimension.spawnParticle('minecraft:heart_particle', {
      x: player.location.x,
      y: player.location.y + 1.2,
      z: player.location.z,
    });
  } catch {
    // Particles are decoration; never let them break the upgrade.
  }
  const key = hearts >= MAX_HEARTS ? 'extra_hearts.gained.max' : 'extra_hearts.gained';
  say(player, key, String(hearts));
  log.info(`${player.name} now has ${hearts} hearts`);
});

// ---------- keeping the hearts applied ----------

world.afterEvents.playerSpawn.subscribe((event) => {
  const { player } = event;
  // The health component may not reflect the saved groups on the spawn tick.
  system.runTimeout(() => ensureHearts(player), 2);
});

system.runInterval(() => {
  for (const player of world.getAllPlayers()) ensureHearts(player);
}, SWEEP_TICKS);

// ---------- mining Heart Ore ----------

function enchantmentLevel(tool: ItemStack | undefined, id: string): number {
  return tool?.getComponent('minecraft:enchantable')?.getEnchantment(id)?.level ?? 0;
}

function canMine(tool: ItemStack | undefined): boolean {
  if (tool === undefined || !tool.hasTag('minecraft:is_pickaxe')) return false;
  return MINING_TIERS.some((tag) => tool.hasTag(tag));
}

function randomInt(min: number, max: number): number {
  return min + Math.floor(Math.random() * (max - min + 1));
}

function dropAt(dimension: Dimension, block: Block, stack: ItemStack): void {
  const center = { x: block.location.x + 0.5, y: block.location.y + 0.5, z: block.location.z + 0.5 };
  dimension.spawnItem(stack, center);
}

world.afterEvents.playerBreakBlock.subscribe((event) => {
  const brokenId = event.brokenBlockPermutation.type.id;
  if (!ORE_IDS.has(brokenId)) return;
  const { player, block, dimension } = event;
  if (player.getGameMode() === GameMode.Creative) return;
  const tool = event.itemStackBeforeBreak;
  if (!canMine(tool)) {
    say(player, 'extra_hearts.ore.tool');
    return;
  }
  if (enchantmentLevel(tool, 'silk_touch') > 0) {
    dropAt(dimension, block, new ItemStack(brokenId, 1));
    return;
  }
  // Fortune adds up to its level in extra fragments, chosen at random.
  const fortune = enchantmentLevel(tool, 'fortune');
  const count = randomInt(DROP_MIN, DROP_MAX) + (fortune > 0 ? randomInt(0, fortune) : 0);
  dropAt(dimension, block, new ItemStack(FRAGMENT_ID, count));
  for (let i = 0; i < XP_ORBS; i++) {
    try {
      dimension.spawnEntity('minecraft:xp_orb', {
        x: block.location.x + 0.5,
        y: block.location.y + 0.5,
        z: block.location.z + 0.5,
      });
    } catch (err) {
      log.warn(`could not spawn xp orb: ${String(err)}`);
      break;
    }
  }
});

// ---------- debug: /scriptevent steveo:hearts <give|status|set N|reset|ore> ----------

function give(player: Player, stack: ItemStack): void {
  const inventory = player.getComponent('minecraft:inventory')?.container;
  if (inventory === undefined) return;
  const leftover = inventory.addItem(stack);
  if (leftover !== undefined) player.dimension.spawnItem(leftover, player.location);
}

function debugStatus(player: Player): void {
  const health = player.getComponent('minecraft:health');
  say(
    player,
    'extra_hearts.debug.status',
    String(totalHearts(player)),
    String(MAX_HEARTS),
    String(getBonus(player)),
    String(Math.round((health?.currentValue ?? 0) / 2)),
    String(Math.round((health?.effectiveMax ?? 0) / 2)),
  );
}

/** A block lookup that treats unloaded chunks and world bounds as "nothing there". */
function blockAt(dimension: Dimension, location: Vector3): Block | undefined {
  try {
    return dimension.getBlock(location);
  } catch {
    return undefined;
  }
}

/**
 * Places random Heart Ore veins in the stone of the loaded chunks around the
 * player, the way world generation would have. Runs as a job so the block
 * lookups are spread over several ticks.
 */
function* seedOre(player: Player, radius: number): Generator<void, void, void> {
  const dimension = player.dimension;
  const originX = Math.floor(player.location.x / 16);
  const originZ = Math.floor(player.location.z / 16);
  let chunks = 0;
  let unloaded = 0;
  let veins = 0;
  let blocks = 0;
  let lookups = 0;

  for (let dx = -radius; dx <= radius; dx++) {
    for (let dz = -radius; dz <= radius; dz++) {
      const chunkX = (originX + dx) * 16;
      const chunkZ = (originZ + dz) * 16;
      if (blockAt(dimension, { x: chunkX, y: SEED_Y_MAX, z: chunkZ }) === undefined) {
        unloaded++;
        continue;
      }
      chunks++;
      for (let vein = 0; vein < SEED_VEINS_PER_CHUNK; vein++) {
        let pos: Vector3 = {
          x: chunkX + randomInt(0, 15),
          y: randomInt(SEED_Y_MIN, SEED_Y_MAX),
          z: chunkZ + randomInt(0, 15),
        };
        let placed = 0;
        // A random walk from the start point, converting stone as it goes.
        for (let step = 0; step < SEED_VEIN_SIZE * 3 && placed < SEED_VEIN_SIZE; step++) {
          const block = blockAt(dimension, pos);
          lookups++;
          const ore = block === undefined ? undefined : SEED_REPLACEABLE.get(block.typeId);
          if (block !== undefined && ore !== undefined) {
            block.setType(ore);
            placed++;
          }
          const axis = randomInt(0, 2);
          const delta = randomInt(0, 1) === 0 ? -1 : 1;
          pos =
            axis === 0
              ? { x: pos.x + delta, y: pos.y, z: pos.z }
              : axis === 1
                ? { x: pos.x, y: pos.y + delta, z: pos.z }
                : { x: pos.x, y: pos.y, z: pos.z + delta };
          if (lookups % SEED_YIELD_EVERY === 0) yield;
        }
        if (placed > 0) {
          veins++;
          blocks += placed;
        }
      }
    }
  }

  log.info(`seeded ${blocks} heart ore in ${veins} veins across ${chunks} chunks (${unloaded} unloaded)`);
  if (player.isValid) {
    say(
      player,
      'extra_hearts.debug.seed.done',
      String(blocks),
      String(veins),
      String(chunks),
      String(unloaded),
    );
  }
}

function debugSeed(player: Player, arg: string | undefined): void {
  const radius = arg === undefined ? SEED_RADIUS_DEFAULT : Number(arg);
  if (!Number.isInteger(radius) || radius < 1 || radius > SEED_RADIUS_MAX) {
    say(player, 'extra_hearts.debug.seed.bad', String(SEED_RADIUS_MAX));
    return;
  }
  const side = radius * 2 + 1;
  say(player, 'extra_hearts.debug.seed.start', `${side}x${side}`);
  system.runJob(seedOre(player, radius));
}

function debugOre(player: Player): void {
  const hit = player.getBlockFromViewDirection({ maxDistance: 8, includeLiquidBlocks: false });
  if (hit === undefined) {
    say(player, 'extra_hearts.debug.ore.none');
    return;
  }
  // Deepslate and tuff get the deepslate look; anything else gets the stone one.
  hit.block.setType(SEED_REPLACEABLE.get(hit.block.typeId) ?? ORE_ID);
  say(player, 'extra_hearts.debug.ore');
}

system.afterEvents.scriptEventReceive.subscribe(
  (event) => {
    if (event.id !== 'steveo:hearts') return;
    const player = event.sourceEntity;
    if (!(player instanceof Player)) return;
    const [command, arg] = event.message.trim().split(/\s+/);
    switch (command) {
      case 'give':
        give(player, new ItemStack(FRAGMENT_ID, 10));
        give(player, new ItemStack(CONTAINER_ID, 1));
        say(player, 'extra_hearts.debug.given');
        break;
      case 'status':
        debugStatus(player);
        break;
      case 'set': {
        const hearts = Number(arg);
        if (!Number.isInteger(hearts) || hearts < BASE_HEARTS || hearts > MAX_HEARTS) {
          say(player, 'extra_hearts.debug.set.bad', String(BASE_HEARTS), String(MAX_HEARTS));
          break;
        }
        setHearts(player, hearts);
        say(player, 'extra_hearts.debug.set', String(hearts));
        break;
      }
      case 'reset':
        setHearts(player, BASE_HEARTS);
        say(player, 'extra_hearts.debug.reset', String(BASE_HEARTS));
        break;
      case 'ore':
        debugOre(player);
        break;
      case 'seed':
        debugSeed(player, arg);
        break;
      default:
        say(player, 'extra_hearts.debug.help');
    }
  },
  { namespaces: ['steveo'] },
);

log.info('loaded');
